package com.eden.hackerdesktopapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import javax.validation.constraints.NotNull;


/**
 * One news model
 *
 * @author Mo Xu
 * @date 2022/09/02
 */
@Data
@DynamoDBTable(tableName = "news")
public class News {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @NotNull
    @DynamoDBAttribute
    private String title;

    @NotNull
    @DynamoDBAttribute
    private String link;
}
