package com.eden.hackerdesktopapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import javax.validation.constraints.NotNull;


/**
 * One podcast item model
 *
 * @author Mo Xu
 * @date 2022/09/12
 */
@Data
@DynamoDBTable(tableName = "podcasts")
public class Podcast {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @NotNull
    @DynamoDBAttribute
    private String title;

    @NotNull
    @DynamoDBAttribute
    private String link;

    @NotNull
    @DynamoDBAttribute
    private String image;
}
