package com.eden.hackerdesktopapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * News provider model
 *
 * @author Mo Xu
 * @date 2022/09/02
 */
@Data
@DynamoDBTable(tableName = "providers")
public class Provider {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String type;

    @DynamoDBAttribute
    private String feedId;

    @DynamoDBAttribute
    private Date lastUpdatedDate;

    @DynamoDBAttribute
    private List<String> newsIds = new ArrayList<>();

    @DynamoDBAttribute
    private String podcastId;
}
