package com.eden.hackerdesktopapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.eden.hackerdesktopapi.constant.enums.UserRoleEnum;
import lombok.Data;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;


/**
 * User model
 *
 * @author Mo Xu
 * @date 2022/08/31
 */
@Data
@DynamoDBTable(tableName = "users")
public class User {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @NotNull
    @Pattern(regexp = "^([a-zA-Z0-9_.-])+@(([a-zA-Z0-9-])+\\.)+([a-zA-Z0-9]{2,4})+$")
    @DynamoDBAttribute
    private String email;

    @NotNull
    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String role = UserRoleEnum.DISABLE.getRole();
}
