# Server port setting
server:
  port: 8080

# Logging setting
logging:
  level:
    org:
      springframework: INFO

# Use hot restart
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev

# JWT setting
jwt:
  # 15 days = 60 * 60 * 24 * 3 seconds
  expiration: 1296000
  prefix: "Bearer "
  authorization: Authorization
  secret: hz1xH4l2WaqaOvv7AK3GtUfFN5vnKKGLZ2u1Ysqdtk4=

# All scheduling
schedule:
  updateEveryFriday: 0 0 1,6,12,18 ? * 5 # Every friday 1,6,12,18 o'clock

# AWS DynamoDB Setting
aws:
  dynamodb:
    accessKey: AKIARQMBEX7R2SSXQXXI
    secretKey: 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
    region: ap-southeast-2
